Updated yelling.py
UQComputingSociety/uqcsbot pull request #543
Opened 2020-10-02 08:12 UTC by paulrusthewalrus

This change should stop the bot from chastising you just because you posted a link in #yelling.

2020-10-02 08:19 UTC, nicklambourne commented
Approach is a bit simple, maybe try a regex match instead? 
e.g. https://stackoverflow.com/a/3809435

2020-10-02 08:23 UTC, paulrusthewalrus commented
Whoops, didn't see your message before I made this new PR. Will try that now :)

2020-10-02 09:10 UTC, kentonlam commented
This closes #534.

2020-10-02 10:46 UTC, nicklambourne requested changes
First, have you tested this in the test workspace? Can you post some screenshots of it working? Will also need a test or two at some point.
Second, I don't think with the current setup that it will work with this one:

> f"DID YOU SAY \n>>>{mutate_minuscule(text)}".upper(),

You either need to put the link back in somehow or remove this from the available options if a link exists.

2020-10-02 10:46 UTC, nicklambourne commented on uqcsbot/scripts/yelling.py
> +import re
`import re` should go first in imports because it's a global import (the whole package).

2020-10-02 14:36 UTC, bradleysigma commented
Odd things may happen if the bot chooses the `f"DID YOU SAY \n>>>{mutate_minuscule(text)}".upper()` response when there is both a link and other, non-link minuscule characters in the message.

2020-10-03 07:36 UTC, paulrusthewalrus commented
Tests for the new PR:
<img width="387" alt="Screen Shot 2020-10-03 at 5 34 07 pm" src="https://user-images.githubusercontent.com/30831649/94986041-c26fa380-059e-11eb-8be8-e0cf00c03b51.png">

2020-10-03 08:30 UTC, nicklambourne commented
Might I suggest using re.match() to identify where the links were so you can reinsert them after analysis and mutation?

2020-11-19 05:18 UTC, paulrusthewalrus commented
<img width="578" alt="Screen Shot 2020-11-19 at 3 18 06 pm" src="https://user-images.githubusercontent.com/30831649/99624732-7a3b1080-2a7a-11eb-93fa-2f8ea1110538.png">

2020-11-21 00:53 UTC, nicklambourne approved these changes

2020-11-21 00:55 UTC, nicklambourne commented
@kentonlam @TomCranitch Can one of you two have a look at this? I changed a little more than I expected to in the cleanup.

2020-11-22 08:15 UTC, TomCranitch approved these changes

2020-11-22 08:41 UTC, merged