Add !link command
UQComputingSociety/uqcsbot pull request #565
Opened 2021-03-29 14:52 UTC by nicklambourne

Adds a user accessible key value store, e.g:

<img width="634" alt="Screen Shot 2021-03-30 at 1 41 15 am" src="https://user-images.githubusercontent.com/9084563/112853873-06c8a000-90f9-11eb-9df3-fbc8a070fa9a.png">
<img width="766" alt="Screen Shot 2021-03-30 at 1 42 39 am" src="https://user-images.githubusercontent.com/9084563/112854097-37a8d500-90f9-11eb-97e0-5e5c62812c21.png">
<img width="792" alt="Screen Shot 2021-03-30 at 1 47 48 am" src="https://user-images.githubusercontent.com/9084563/112854823-f238d780-90f9-11eb-83a3-a3f8eb303a38.png">

This has the added benefit of adding the "brain" back into the bot and provides a template for further (and easy) use of the database though sqlalchemy orm models.

[ ] Still needs tests and more thorough manual testing.
[ ] Need to set up the UQCSBOT_DB_URI env var in the server config.

2021-04-15 05:46 UTC, kentonlam requested changes
Looks pretty good and will surely be useful in future. The message formatting is a bit arcane and should be cleaned up, but apart from that looks good. 

Do we need the empty test/test_utils.py file?

2021-04-15 05:46 UTC, kentonlam commented on uqcsbot/models.py
> +        return f"<Link: ({self.key}, {self.channel} = {self.value})>"
Nit: Can this be a more conventional `Link(self.key, ...)` form?

2021-04-15 05:46 UTC, kentonlam commented on uqcsbot/scripts/link.py
> +    :param link_scope: required to be True if the association is to be specific to the channel
Comment references old bool behaviour.

2021-04-15 05:46 UTC, kentonlam commented on uqcsbot/scripts/link.py
> +                   link_scope: LinkScope) -> Tuple[Optional[str], Optional[str]]:
link_scope should be Optional?

2021-04-15 05:46 UTC, kentonlam commented on uqcsbot/scripts/link.py
> +        channel_name = bot.channels.get(command.channel_id).name
Don't need else block because of return and can just use channel.name instead.

2021-04-15 05:46 UTC, kentonlam commented on uqcsbot/scripts/link.py
> +                   f"No link found for key: `{args.key}`{if_channel_flag}"
A bit of a mess with all the ternaries 😅 Can we split it into something like this instead?
```python
channel_text = f" in channel `{channel_name}`" if args.channel_flag else ""
source_text = source if source == 'global' else channel_name
result_text = link_value if link_value else
    f"No link found for key: `{args.key}`" + channel_text
response = f"{args.key} ({source_text}): {result_text}"
```

2021-04-15 05:46 UTC, kentonlam commented on uqcsbot/scripts/link.py
> +        response = f"{args.key} ({channel_name if args.channel_flag else 'global'}): " \
Not as bad as above, but can we pull the ternary into its own variable?

2021-04-17 07:53 UTC, kentonlam approved these changes
Looks good, thanks for cleaning it up. What should UQCSBOT_DB_URI be on the server?

2021-04-17 10:13 UTC, JamesDearlove approved these changes
Looks like a pretty useful feature, I approve

2021-04-19 14:47 UTC, merged